# Alembic Configuration for IntelliCare
# This file contains the configuration needed to get Alembic to work with your project.

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be named with an ordering prefix and uncomment sqlalchemy.url line
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# string value is passed to dateutil.tz.gettz()
# leave blank for localtime
sqlalchemy.url = 

# [loggers]
# keys = root,sqlalchemy,alembic

# [handlers]
# keys = console

# [formatters]
# keys = generic

# [logger_root]
# level = WARN
# handlers = console
# qualname =

# [logger_sqlalchemy]
# level = WARN
# handlers =
# qualname = sqlalchemy.engine

# [logger_alembic]
# level = INFO
# handlers =
# qualname = alembic

# [handler_console]
# class = StreamHandler
# args = (sys.stderr,)
# level = NOTSET
# formatter = generic

# [formatter_generic]
# format = %(levelname)-5.5s [%(name)s] %(message)s
# datefmt = %H:%M:%S
